// v5.0.0 ile gelen özelliklerin metinleri (Otomasyon & Efektler, paket
// favori/etiket/arama, sürüm notları, ayar yedekleme, editör kontur/gölge).
// lang.js'teki LANG nesnesine eklenir; eksik anahtar t() içinde TR'ye düşer.
Object.assign(LANG.tr, {
  settings_tab_extras: 'Otomasyon & Efektler',
  close_tray_title: 'Kapatınca Tepsiye Küçült',
  close_tray_desc: '✕ düğmesi uygulamayı kapatmaz, sistem tepsisine küçültür; kısayollar ve otomasyon çalışmaya devam eder.',
  close_tray_on: 'Kapatınca tepsiye küçültülecek', close_tray_off: 'Kapatınca uygulamadan çıkılacak',
  tray_open: 'RBX Cursor Studio\u2019yu Aç', tray_quit: 'Çıkış',
  autolaunch_title: 'Roblox Açılınca Son Paketi Uygula',
  autolaunch_desc: 'Roblox başladığında en son kullandığın paket otomatik uygulanır.',
  autolaunch_on: 'Roblox açılınca son paket uygulanacak', autolaunch_off: 'Otomatik uygulama kapatıldı',
  scheduler_title: 'Zamanlı / Rastgele Paket Değiştirici',
  scheduler_desc: 'Belirlediğin aralıkta paketler otomatik değişir. Roblox kapalıysa o tur atlanır.',
  scheduler_mode: 'Mod', scheduler_mode_random: 'Rastgele', scheduler_mode_seq: 'Sırayla',
  scheduler_interval: 'Aralık (dakika)', scheduler_packs: 'Dahil edilecek paketler (boş = hepsi)',
  scheduler_on: 'Paket değiştirici açıldı', scheduler_off: 'Paket değiştirici kapatıldı',
  scheduler_applied: '"{name}" paketine geçildi',
  trail_title: 'Cursor İzi Efekti (Beta)', trail_desc: 'İmlecinin arkasında yıldız, duman, ateş gibi efektler çizer (tüm ekranda). Beta: bilgisayarını yavaşlatırsa uzunluğu azalt ya da kapat, ardından bize bildir.',
  trail_everywhere: 'Oyun dışında da kullan (kapalıyken iz sadece Roblox çalışırken görünür)', trail_everywhere_on: 'İz artık her yerde görünecek', trail_everywhere_off: 'İz sadece Roblox çalışırken görünecek',
  trail_style: 'Stil', trail_style_classic: 'Klasik', trail_style_stars: '⭐ Yıldız', trail_style_sparkles: '✨ Kıvılcım', trail_style_smoke: '💨 Duman', trail_style_fire: '🔥 Ateş', trail_style_hearts: '❤ Kalp', trail_style_rainbow: '🌈 Gökkuşağı',
  trail_color: 'Renk', trail_length: 'Uzunluk', trail_on: 'Cursor izi açıldı', trail_off: 'Cursor izi kapatıldı',
  clicksound_title: 'Tıklama Sesi (Beta)',
  clicksound_desc: 'Roblox ön plandayken her sol tıkta kısa bir ses çalar. Native yardımcının (cursor_helper.exe) bu sürümle yeniden derlenmiş olması gerekir.',
  clicksound_volume: 'Ses seviyesi', clicksound_test: '🔊 Dene',
  clicksound_pick: '📁 Ses Dosyası Yükle', clicksound_clear: 'Varsayılana Dön',
  clicksound_file_ok: 'Özel tıklama sesi yüklendi ✓', clicksound_file_cleared: 'Varsayılan tıklama sesine dönüldü', clicksound_bad_file: 'Bu ses dosyası okunamadı. WAV, MP3 veya OGG dene.',
  clicksound_on: 'Tıklama sesi açıldı', clicksound_off: 'Tıklama sesi kapatıldı',
  discord_title: 'Discord Rich Presence',
  discord_desc: 'Discord açıksa otomatik olarak profilinde gösterilir. İstemezsen Discord > Ayarlar > Etkinlik Gizliliği kısmından kapatabilirsin.',
  discord_advanced: 'Gelişmiş: kendi Client ID\u2019n (isteğe bağlı, boş bırakabilirsin)',
  discord_status_connected: 'Discord bulundu — durum gösteriliyor', discord_status_waiting: 'Discord aranıyor… (Discord açılınca otomatik bağlanır)', discord_status_off: 'Kapalı',
  discord_unavailable: 'discord-rpc paketi kurulu değil (npm install çalıştır).',
  discord_on: 'Discord durumu açıldı', discord_off: 'Discord durumu kapatıldı', discord_need_id: 'Client ID sadece rakamlardan oluşmalı',
  changelog_title: 'Sürüm Notları', changelog_desc: 'GitHub\u2019daki en son sürümün değişiklik notlarını göster.',
  changelog_btn: 'Notları Göster', changelog_close: 'Tamam', changelog_empty: 'Bu sürüm için not bulunamadı.',
  changelog_error: 'Sürüm notları alınamadı.',
  backup_title: 'Ayarları Yedekle / Geri Yükle',
  backup_desc: 'Tüm uygulama ayarlarını tek bir JSON dosyasına kaydet ya da başka bir yedekten yükle (paketler dahil değildir).',
  backup_export: 'Dışa Aktar', backup_import: 'İçe Aktar',
  backup_exported: 'Ayarlar dışa aktarıldı ✓', backup_imported: 'Ayarlar içe aktarıldı ✓', backup_error: 'Ayar yedeği işlenemedi:',
  pack_search_placeholder: 'Paket ara (ad veya etiket)…', pack_filter_fav: '⭐ Favoriler',
  pack_fav: 'Favori', pack_tags_edit: 'Etiketleri düzenle', pack_tags_placeholder: 'etiket1, etiket2',
  pack_share: 'Paylaş', pack_share_hint: 'Paket kaydedildi. Açılan GitHub sayfasına dosyayı sürükleyip bırak.',
  editor_effects: 'Kontur & Gölge', editor_outline: 'Kontur Ekle', editor_shadow: 'Gölge Ekle',
  editor_effect_color: 'Renk', editor_effect_thickness: 'Kalınlık', editor_effect_done: 'Efekt uygulandı ✓',
  editor_access_preset: '♿ Erişilebilirlik: Kalın Kontur', editor_access_done: 'Yüksek kontrastlı kontur eklendi ✓'
});
Object.assign(LANG.en, {
  settings_tab_extras: 'Automation & Effects',
  close_tray_title: 'Close to Tray',
  close_tray_desc: 'The ✕ button minimizes to the system tray instead of quitting; shortcuts and automation keep running.',
  close_tray_on: 'Closing will minimize to the tray', close_tray_off: 'Closing will quit the app',
  tray_open: 'Open RBX Cursor Studio', tray_quit: 'Quit',
  autolaunch_title: 'Apply Last Pack When Roblox Starts',
  autolaunch_desc: 'When Roblox launches, the pack you used last is applied automatically.',
  autolaunch_on: 'Last pack will be applied when Roblox starts', autolaunch_off: 'Auto-apply turned off',
  scheduler_title: 'Timed / Random Pack Switcher',
  scheduler_desc: 'Packs change automatically at the interval you set. If Roblox is closed, that round is skipped.',
  scheduler_mode: 'Mode', scheduler_mode_random: 'Random', scheduler_mode_seq: 'In order',
  scheduler_interval: 'Interval (minutes)', scheduler_packs: 'Packs to include (empty = all)',
  scheduler_on: 'Pack switcher turned on', scheduler_off: 'Pack switcher turned off',
  scheduler_applied: 'Switched to "{name}"',
  trail_title: 'Cursor Trail Effect (Beta)', trail_desc: 'Draws effects like stars, smoke or fire behind your cursor (across the whole screen). Beta: if it slows your PC, lower the length or turn it off and let us know.',
  trail_everywhere: 'Also use outside the game (when off, the trail only shows while Roblox is running)', trail_everywhere_on: 'Trail will show everywhere', trail_everywhere_off: 'Trail will only show while Roblox is running',
  trail_style: 'Style', trail_style_classic: 'Classic', trail_style_stars: '⭐ Stars', trail_style_sparkles: '✨ Sparkles', trail_style_smoke: '💨 Smoke', trail_style_fire: '🔥 Fire', trail_style_hearts: '❤ Hearts', trail_style_rainbow: '🌈 Rainbow',
  trail_color: 'Color', trail_length: 'Length', trail_on: 'Cursor trail turned on', trail_off: 'Cursor trail turned off',
  clicksound_title: 'Click Sound (Beta)',
  clicksound_desc: 'Plays a short sound on every left click while Roblox is focused. Requires the native helper (cursor_helper.exe) to be rebuilt with this version.',
  clicksound_volume: 'Volume', clicksound_test: '🔊 Test',
  clicksound_pick: '📁 Upload Sound File', clicksound_clear: 'Reset to Default',
  clicksound_file_ok: 'Custom click sound loaded ✓', clicksound_file_cleared: 'Back to the default click sound', clicksound_bad_file: 'Could not read this audio file. Try WAV, MP3 or OGG.',
  clicksound_on: 'Click sound turned on', clicksound_off: 'Click sound turned off',
  discord_title: 'Discord Rich Presence',
  discord_desc: 'Shown on your Discord profile automatically when Discord is open. To turn it off, use Discord > Settings > Activity Privacy.',
  discord_advanced: 'Advanced: your own Client ID (optional, leave empty)',
  discord_status_connected: 'Discord found — presence is showing', discord_status_waiting: 'Looking for Discord… (connects automatically when it opens)', discord_status_off: 'Off',
  discord_unavailable: 'The discord-rpc package is not installed (run npm install).',
  discord_on: 'Discord presence turned on', discord_off: 'Discord presence turned off', discord_need_id: 'Client ID must be digits only',
  changelog_title: 'Release Notes', changelog_desc: 'Show the release notes of the latest version on GitHub.',
  changelog_btn: 'Show Notes', changelog_close: 'OK', changelog_empty: 'No notes found for this release.',
  changelog_error: 'Could not fetch release notes.',
  backup_title: 'Back Up / Restore Settings',
  backup_desc: 'Save all app settings to a single JSON file or load them from another backup (packs are not included).',
  backup_export: 'Export', backup_import: 'Import',
  backup_exported: 'Settings exported ✓', backup_imported: 'Settings imported ✓', backup_error: 'Could not process settings backup:',
  pack_search_placeholder: 'Search packs (name or tag)…', pack_filter_fav: '⭐ Favorites',
  pack_fav: 'Favorite', pack_tags_edit: 'Edit tags', pack_tags_placeholder: 'tag1, tag2',
  pack_share: 'Share', pack_share_hint: 'Pack saved. Drag and drop the file onto the GitHub page that just opened.',
  editor_effects: 'Outline & Shadow', editor_outline: 'Add Outline', editor_shadow: 'Add Shadow',
  editor_effect_color: 'Color', editor_effect_thickness: 'Thickness', editor_effect_done: 'Effect applied ✓',
  editor_access_preset: '♿ Accessibility: Bold Outline', editor_access_done: 'High-contrast outline added ✓'
});
