
const LANG = {
  tr: {
    'editor_drag_hint':'Görseli sürükleyerek konumlandır','editor_position':'Konum','editor_color':'Renk','editor_help_title':'Nasıl çalışır?',
    'ready':'Hazır','btn_pick':'Seç','btn_edit':'Düzenle','btn_remove':'Kaldır',
    'chip_custom':'Özel','chip_original':'Orijinal','chip_missing':'Dosya yok',
    'cursor_remove_confirm':'\"{name}\" imleci Roblox\u2019un orijinaline döndürülsün mü?','cursor_removed':'{name} orijinaline döndürüldü ✓',
    'cursor_edit_missing':'Düzenlenecek bir imleç dosyası bulunamadı. Önce \"Seç\" ile bir görsel ekle.',
    'active_empty_title':'Roblox imleç klasörü bulunamadı','active_empty_desc':'Roblox\u2019u bir kez açıp kapattıktan sonra yenile düğmesine bas.',
    'dock_label':'Ana gezinme',
    'home':'Ana Sayfa','backgrounds':'Arkaplan','packs':'Paketler','history':'Geçmiş','settings':'Ayarlar',
    'minimize':'Küçült','maximize':'Büyüt','close':'Kapat','welcome':'Hoş geldin, Carl',
    'welcome_sub':'İmleçlerini kişiselleştirmeye devam et','restore':'Orijinale Dön',
    'active_title':'Şu An Aktif Olan Cursor','checking':'Kontrol ediliyor…','refresh':'Aktif cursorları yenile',
    'my_cursors':'İmleçlerim','my_cursors_sub':'Yeni bir görsel seçmek için tıkla — önceki seçimlerini Ayarlar › Geçmiş bölümünde bulabilirsin',
    'save':'Kaydet','roblox_active':'Roblox Aktif','roblox_error':'Roblox hatası','roblox_not_found':'Roblox bulunamadı','status_error':'Durum kontrol edilemedi',
    'background_default':'Varsayılana Dön','import':'İçe Aktar','saved_packs':'Kayıtlı Paketler','new_pack':'+ Yeni Paket',
    'history_title':'Geçmiş','settings_title':'Ayarlar','roblox_version':'Roblox Sürümü','auto_reinstall':'Otomatik Düzeltme',
    'auto_reinstall_desc':'Roblox güncellendiğinde kayıtlı imleçlerini yeni sürüme otomatik olarak yeniden kurar.',
    'start_boot':'Windows Başlangıcında Aç','start_boot_desc':'Bilgisayar açıldığında uygulama otomatik olarak başlasın.',
    'minimize_tray':'Kapatınca Tepsiye Küçül','minimize_tray_desc':'Pencereyi kapatınca uygulama çıkmaz, sistem tepsisinde çalışmaya devam eder. Tepsi simgesinden tekrar açabilir ya da tamamen çıkabilirsin.',
    'tray_on':'Kapatınca tepsiye küçülecek','tray_off':'Kapatınca uygulama tamamen çıkacak','tray_applied_toast':'Tepsiden \"{name}\" paketi uygulandı ✓',
    'gamewatch_title':'Oyuna Göre Otomatik Paket','gamewatch_desc':'Roblox\'un kendi log dosyalarını (salt okunur) izleyerek açtığın oyuna göre eşlediğin paketi otomatik uygular. Roblox sürecine dokunmaz, ağa istek atmaz.',
    'gamewatch_unfinished':'⚠️ Ayrıştırma mantığı gerçek log örnekleriyle henüz tamamlanmadı; bu açık olsa bile şu an hiçbir paketi otomatik değiştirmez.',
    'gamewatch_mapping_title':'Oyun → Paket Eşlemesi','gamewatch_add_current':'Son oynadığım oyunu ekle',
    'gamewatch_placeid_placeholder':'placeId (ör. 123456789)','gamewatch_add_mapping':'Ekle',
    'gamewatch_on':'Oyuna göre otomatik paket açıldı (henüz aktif çalışmıyor — bkz. açıklama)','gamewatch_off':'Oyuna göre otomatik paket kapatıldı',
    'gamewatch_mapping_added':'Eşleme eklendi','gamewatch_mapping_removed':'Eşleme kaldırıldı','gamewatch_need_placeid_and_pack':'placeId ve paket seç',
    'gamewatch_last_seen_none':'Henüz bir oyun tespit edilmedi (ayrıştırıcı tamamlanmadan bu normal — üstteki uyarıya bak). placeId\'yi elle yazabilirsin.',
    'gamewatch_remove':'Kaldır','gamewatch_applied_toast':'Oyuna göre \"{name}\" paketi otomatik uygulandı ✓',
    'about':'Hakkında','about_text':'RBX Cursor Studio — Yapımcı: Carl<br>© 2026 Carl. Tüm hakları saklıdır. Bu yazılımın yapımcının yazılı izni olmadan kopyalanması, değiştirilip dağıtılması veya paylaşılması yasaktır.',
    'editor_title':'İmleci Düzenle','size':'Boyut (büyüt / küçült)','auto_fit':'Otomatik Boyutlandır + Ortala','center':'Sadece Ortala','reset_size':'Boyutu Sıfırla',
    'manual_center':'Manuel Ortala (Tam Merkez)','manual_center_help':'Otomatik ortalama, görselin şeffaf olmayan kısmını algılayıp ona göre konumlandırır — bazı görsellerde bu algılama beklediğin sonucu vermeyebilir. Böyle durumlarda "Manuel Ortala" görseli algılama yapmadan doğrudan 64×64 alanın tam merkezine yerleştirir; X/Y kutularından ya da sürükleyerek de pikseli piksele ince ayar yapabilirsin.',
    'offset_x':'X Konumu','offset_y':'Y Konumu','manual_center_done':'Görsel tam merkeze yerleştirildi ✓',
    'editor_help':'Yeni görseller, Roblox’un varsayılan cursor ölçü ve konumları referans alınarak otomatik boyutlandırılır ve ortalanır. İstersen sürükleyerek konumu değiştirebilir, boyut çubuğuyla büyütüp küçültebilirsin. Piksel netliğini korumak için yumuşatma kapalıdır.',
    'cancel':'İptal','create':'Oluştur','normal':'Normal Durum','click':'Tıklama','text':'Yazı Modu','shiftlock':'Shift Lock','choose_image':'Görsel seç','roblox_file':'Roblox dosyası',
    'not_registered':'Kayıtlı bir pakete ait değil (özgün/özel)','pack_applied':'paketinde uygulandı ✓','pack_apply':'Uygula','pack_remove':'Kaldır','applied':'Uygulandı ✓',
    'no_packs':'Henüz kayıtlı paket yok.','packs_load_error':'Paketler yüklenemedi.','no_history':'Henüz geçmiş kayıt yok.','history_load_error':'Geçmiş yüklenemedi.',
    'use':'Kullan','delete':'Sil','backgrounds_load_error':'Arkaplanlar yüklenemedi:','background_imported':'Arkaplan içe aktarıldı ✓','background_delete':'Arkaplanı sil','background_delete_confirm':'"{name}" arkaplanını silmek istediğine emin misin? Bu dosya uygulama klasörlerinden tamamen silinecek.','background_deleted':'Arkaplan silindi ✓',
    'default_bg_missing':'Varsayılan arkaplan bulunamadı','default_bg_restored':'Varsayılan arkaplana dönüldü ✓','settings_read_error':'Ayarlar okunamadı:',
    'settings_load_error':'Ayarlar yüklenemedi, varsayılanlar kullanılıyor','status_unavailable':'Durum alınamadı',
    'auto_on':'Otomatik düzeltme açıldı','auto_off':'Otomatik düzeltme kapatıldı','boot_on':'Windows başlangıcında açılacak','boot_off':'Windows başlangıcında açılma kapatıldı',
    'file_select_error':'Dosya seçilemedi:','image_invalid':'Görsel okunamadı (geçersiz boyut). Başka bir dosya dene.',
    'cursor_auto_fit':'Cursor otomatik boyutlandırıldı ve ortalandı ✓','image_read_error':'.cur/.ico içindeki görsel okunamadı.',
    'cursor_file_error':'.cur/.ico dosyası okunamadı:','image_load_error':'Görsel yüklenemedi. Dosya bozuk ya da desteklenmeyen bir biçimde olabilir.',
    'preview_error':'Önizleme çizilemedi:','cursor_centered':'Cursor ortalandı ✓','save_error':'Kaydetme hatası:','error':'Hata:',
    'restore_done':'imleç orijinaline döndürüldü ✓','no_backup':'Geri alınacak yedek bulunamadı','pack_name':'Paket adı:',
    'pack_saved':'paketi kaydedildi ✓','pack_applied_toast':'uygulandı ✓','pack_removed':'kaldırıldı','history_applied':'uygulandı ✓','history_deleted':'Geçmişten silindi',
    'background_error':'Arkaplanlar yüklenemedi:','background_import_error':'Arkaplan içe aktarıldı ✓','language':'Dil / Language','turkish':'Türkçe','english':'English',
    'roblox_updated':'Roblox güncellendi — {count} imleç otomatik olarak yeniden kuruldu ✓','restore_done_count':'{count} imleç orijinaline döndürüldü ✓','pack_saved_named':'"{name}" paketi kaydedildi ✓','saved_named':'"{name}" paketi kaydedildi ✓',
    'colorize':'Renklendir (siyah-beyazdan renk üret)','hue':'Renk Tonu','color_variations':'Renk Varyasyonları Oluştur',
    'import_pack':'📥 İçe Aktar','pack_from_active':'🖱️ Aktif Cursoru Pakete Çevir','pack_from_active_short':'Aktif Cursoru Pakete Çevir','pack_export':'Dışa Aktar','pack_dropzone_hint':'Bir arkadaşının paylaştığı .rbxcursor / .zip dosyasını buraya sürükleyip bırakabilirsin.',
    'pack_imported':'"{name}" paketi içe aktarıldı ✓','pack_exported':'"{name}" paketi dışa aktarıldı ✓','pack_import_error':'Paket içe aktarılamadı:','pack_export_error':'Paket dışa aktarılamadı:',
    'quickswitch_title':'Hızlı Paket Geçişi','quickswitch_desc':'Her paket için kendi klavye kısayolunu belirle. Roblox içindeyken de çalışır.',
    'quickswitch_assign':'⌨️ Tuş Ata','quickswitch_press':'Bir kısayol tuş kombinasyonuna bas…','quickswitch_saved':'Kısayol kaydedildi ✓',
    'quickswitch_none':'— Yok —','quickswitch_saved':'Kısayol kaydedildi ✓','quickswitch_applied_toast':'Kısayol (Ctrl+Alt+{slot}) ile "{name}" uygulandı ✓','quickswitch_error_toast':'Kısayol uygulanamadı:',
    'nav_animation':'Animasyon','settings_tab_general':'Genel','history_enabled':'Geçmişi Kaydet','history_enabled_desc':'Düzenleyicide kaydettiğin imleçler Geçmiş listesine eklenir. Kapatırsan yeni kayıt eklenmez; mevcut geçmiş silinmez.','history_on':'Geçmiş kaydı açıldı','history_off':'Geçmiş kaydı kapatıldı',
    'donate':'Destek','donate_tooltip':'Bağışların sayesinde daha hızlı güncelleme ve fix geliyor — projeyi destekle ☕',
    'animcursor':'Animasyonlu','animcursor_title':'Animasyonlu İmleç (Beta)','animcursor_desc':'🧪 Beta özellik: otomatik durum tespiti bazı oyunlarda ara sıra yanılabilir. Her durum için bir .ANI dosyası seç. Animasyon atanan durumda Roblox\u2019un sabit imleci gizlenir, yerine native animasyonlu imleç gösterilir. Kaldırılırsa statik imleç geri döner.','animcursor_none':'Atanmadı — gerçek statik imleç kullanılıyor','animcursor_applied':'Animasyonlu imleç uygulandı ✓','animcursor_removed':'Animasyon kaldırıldı, statik imleç geri döndü ✓',
    'context_preview':'Bağlamda Önizle','context_preview_title':'Bağlamda Önizleme','context_preview_help':'Cursoru gerçek piksel boyutunda, oyun içi bir sahne üzerinde test et.',
    'context_play':'OYNA','context_chat_placeholder':'Sohbete yaz...','context_shiftlock':'Shift Lock modunu dene','context_no_cursor':'Bu imleç türü için henüz bir görsel kaydedilmemiş.',
    'context_play_toast':'🎮 Bu bir oyun değil, sadece imleç deneme sahnesi — imleçlerin böyle görünüyor!',
    'color_changer':'Renk Değiştir','color_changer_title':'İmleç Rengini Değiştir',
    'color_changer_help':'Şu an kullanılan tüm imleçleri, boyut ve konumlarına dokunmadan seçtiğin renk tonuna boyar.',
    'color_changer_apply':'🎨 Uygula','color_changer_none':'Renklendirilecek aktif bir imleç bulunamadı. Önce Roblox’ta en az bir imleç uygulanmış olmalı.',
    'color_changer_applied':'İmleç rengi güncellendi ✓',
    'pack_name_required':'Paket adı gerekli.','select_one_cursor_required':'En az bir cursor seçmelisin.',
    'pack_cursor_selection_title':'Cursor Seçimi','pack_cursor_selection_hint':'Pakete dahil edilecek cursorları seç. Özel/custom cursorların varsa mevcut seçimler otomatik kullanılır.',
    'packs_tab_normal':'Paketler','packs_tab_animated':'🎞 Animasyonlu Paketler','no_anim_packs':'Henüz animasyonlu paket yok.','pack_anim_badge':'Animasyonlu paket',
    'new_anim_pack':'+ Yeni Animasyonlu Paket','new_anim_pack_states_title':'Dahil Edilecek Animasyonlar','new_anim_pack_states_hint':'Şu an .ani atanmış durumlar listelenir; bu paketle birlikte hem animasyon hem de o anki cursor görseli kaydedilir.',
    'new_anim_pack_none_assigned':'Henüz hiçbir duruma animasyon (.ani) atanmamış. Önce Animasyonlu İmleç sekmesinden bir .ani seç.','new_anim_pack_none_selected':'En az bir animasyon durumu seçmelisin.',
    'context_preview_tooltip':'İmleçlerini sahte bir Roblox ekranı üzerinde dene','color_changer_tooltip':'Şu an kullandığın tüm imleçlerin rengini tek seferde değiştir',
    'restore_tooltip':'Roblox\u2019un kendi orijinal imleçlerine geri dön','pack_from_active_tooltip':'Şu an kullanılan cursorları yeni bir pakete kaydet',
    'app_tagline_tooltip':'RBX Cursor Studio — Yapımcı: Carl',
    'update_install_btn':'İndir ve kur (v{v})','update_available_inapp':'Yeni sürüm var: v{v} (şu an v{cur}). Uygulama içinden indirilip kurulur.','update_downloading_btn':'İndiriliyor… %{p}','update_downloading':'Güncelleme indiriliyor: %{p}','update_restart_btn':'Yeniden başlat ve güncelle','update_ready':'v{v} indirildi — kurmak için yeniden başlat','update_ready_toast':'Güncelleme hazır (v{v}). Ayarlar > Güncellemeler\'den yeniden başlatıp kurabilirsin.','update_restarting':'Uygulama kapanıp güncellenecek…','update_retry_btn':'Tekrar dene','update_dl_error':'Güncelleme indirilemedi.',
    'update_title':'Güncellemeler','update_desc':'Açılışta GitHub\'a tek bir sürüm sorusu gönderir; yeni sürüm varsa haber verir. İndirme ve kurulum yalnızca sen onaylayınca başlar.',
    'update_check_btn':'Şimdi kontrol et','update_checking':'Kontrol ediliyor…','update_auto_title':'Açılışta otomatik kontrol','update_auto_on':'Açılışta güncelleme kontrolü açıldı','update_auto_off':'Açılışta güncelleme kontrolü kapatıldı',
    'update_available':'Yeni sürüm var: v{v} (şu an v{cur}) — indirmek için tıkla','update_available_toast':'Yeni sürüm var: v{v}. Ayarlar > Güncellemeler\'den ya da sol üstteki sürüm etiketinden indirebilirsin.','update_open_btn':'Sürümü aç',
    'update_uptodate':'Güncelsin (v{cur})','update_error':'Kontrol edilemedi (internet bağlantını kontrol et)','update_error_rate':'GitHub şu an çok fazla istek aldı; biraz sonra tekrar dene',
    'animcursor_size_label':'Boyut ×','animcursor_speed_label':'Hız ×','animcursor_fps_label':'FPS (0 = ANI orijinal)',
    'animcursor_center_auto':'Otomatik Ortala (tam merkez)','animcursor_hotspot_x':'Hotspot X','animcursor_hotspot_y':'Hotspot Y',
    'animcursor_hotspot_hint':'(-1 = ANI\u2019nin kendi hotspot\u2019u — Otomatik Ortala kapalıyken geçerli)',
    'animcursor_pick_btn':'📂 .ANI Seç','animcursor_preview_btn':'👁️ Önizle (6sn)','animcursor_preview_running':'👁️ Masaüstünde 6sn...','animcursor_clear_btn':'🗑️ Kaldır',
    'animcursor_live_title':'Şu an aktif','animcursor_global_title':'Takip Hassasiyeti',
    'animcursor_global_desc':'Fare imleci takip döngüsünün yenileme aralığı — tüm durumlar (arrow/click/text/shiftlock) için geçerli.',
    'animcursor_toggle_title':'Animasyonu Aç / Kapat Kısayolu','animcursor_toggle_desc':'Bu tuşa basınca animasyonlu imleç gizlenir ve önceki (statik) imleçlerin geri gelir; tekrar basınca animasyon geri döner (Roblox içindeyken de çalışır). Roblox imleç dosyalarını yalnızca açılışta okuyorsa değişikliğin görünmesi için Roblox\'u yeniden başlatman gerekebilir. Açık/kapalı durumun hatırlanır; bir sonraki açılışta kaldığın yerden devam eder.',
    'animcursor_toggle_on':'Animasyon: AÇIK (kapatmak için tıkla)','animcursor_toggle_off':'Animasyon: KAPALI (açmak için tıkla)','animcursor_toggled_on':'Animasyonlu imleç açıldı ✓','animcursor_toggled_off':'Animasyonlu imleç kapatıldı',
    'animcursor_track_interval':'Takip Aralığı','animcursor_track_hint':'Düşük ms = daha akıcı/hızlı takip (biraz daha fazla CPU), yüksek ms = daha az yenileme.',
    'animcursor_states_title':'Durum Animasyonları','animcursor_states_sub':'{n}/4 durumda animasyon atandı','animcursor_assigned':'ANI Atandı','animcursor_unassigned':'Atanmadı',
    'animcursor_shared_title':'Ayarlar — Tüm Durumlar İçin Ortak','animcursor_shared_hint':'Burada yaptığın değişiklik dört duruma da aynı anda uygulanır.',
    'animcursor_fullscreen_warning':'⚠️ Roblox <strong>tam ekran (exclusive fullscreen)</strong> modundaysa hiçbir overlay (bizimki dahil, Discord/Steam/RTSS de aynı) oyunun üstüne çizilemez — bu Windows\u2019un kısıtıdır. Roblox ayarlarından "Pencereli Tam Ekran / Borderless" moda geçmen gerekir. Animasyon görünmüyorsa önce <strong>Önizle</strong> butonuyla dene: bu, Roblox açık olmasa bile masaüstünde 6 saniyeliğine gösterir.'
  },
  en: {
    'editor_drag_hint':'Drag the image to reposition it','editor_position':'Position','editor_color':'Color','editor_help_title':'How does it work?',
    'ready':'Ready','btn_pick':'Choose','btn_edit':'Edit','btn_remove':'Remove',
    'chip_custom':'Custom','chip_original':'Original','chip_missing':'No file',
    'cursor_remove_confirm':'Restore \"{name}\" to Roblox\u2019s original?','cursor_removed':'{name} restored to original ✓',
    'cursor_edit_missing':'There is no cursor file to edit yet. Use \"Choose\" to add an image first.',
    'active_empty_title':'Roblox cursor folder not found','active_empty_desc':'Open Roblox once, close it, then press the refresh button.',
    'dock_label':'Main navigation',
    'home':'Home','backgrounds':'Backgrounds','packs':'Packs','history':'History','settings':'Settings',
    'minimize':'Minimize','maximize':'Maximize','close':'Close','welcome':'Welcome, Carl',
    'welcome_sub':'Keep personalizing your cursors','restore':'Restore Defaults',
    'active_title':'Currently Active Cursors','checking':'Checking…','refresh':'Refresh active cursors',
    'my_cursors':'My Cursors','my_cursors_sub':'Click to choose a new image — you can find previous selections in Settings › History',
    'save':'Save','roblox_active':'Roblox Active','roblox_error':'Roblox error','roblox_not_found':'Roblox not found','status_error':'Unable to check status',
    'background_default':'Restore Default','import':'Import','saved_packs':'Saved Packs','new_pack':'+ New Pack',
    'history_title':'History','settings_title':'Settings','roblox_version':'Roblox Version','auto_reinstall':'Automatic Repair',
    'auto_reinstall_desc':'Automatically reinstalls your saved cursors for the new version when Roblox is updated.',
    'start_boot':'Launch at Windows Startup','start_boot_desc':'Automatically start the app when the computer boots.',
    'minimize_tray':'Minimize to Tray on Close','minimize_tray_desc':'Closing the window won\'t quit the app — it keeps running in the system tray. Reopen it from the tray icon, or quit from there entirely.',
    'tray_on':'Will minimize to tray on close','tray_off':'Will fully quit on close','tray_applied_toast':'Applied pack \"{name}\" from tray ✓',
    'gamewatch_title':'Automatic Pack by Game','gamewatch_desc':'Watches Roblox\'s own log files (read-only) and auto-applies the pack you mapped to the game you open. Doesn\'t touch the Roblox process, no network requests.',
    'gamewatch_unfinished':'⚠️ The parsing logic isn\'t finished with real log samples yet; even if this is on, it currently never switches a pack automatically.',
    'gamewatch_mapping_title':'Game → Pack Mapping','gamewatch_add_current':'Add my last played game',
    'gamewatch_placeid_placeholder':'placeId (e.g. 123456789)','gamewatch_add_mapping':'Add',
    'gamewatch_on':'Automatic pack by game turned on (not active yet — see description)','gamewatch_off':'Automatic pack by game turned off',
    'gamewatch_mapping_added':'Mapping added','gamewatch_mapping_removed':'Mapping removed','gamewatch_need_placeid_and_pack':'Pick a placeId and a pack',
    'gamewatch_last_seen_none':'No game detected yet (expected until the parser is finished — see the warning above). You can type the placeId manually.',
    'gamewatch_remove':'Remove','gamewatch_applied_toast':'Auto-applied pack \"{name}\" for this game ✓',
    'about':'About','about_text':'RBX Cursor Studio — Created by: <b>Carl</b><br>© 2026 Carl. All rights reserved. Copying, modifying, distributing, or sharing this software without the creator’s written permission is prohibited.',
    'editor_title':'Edit Cursor','size':'Size (increase / decrease)','auto_fit':'Auto Fit + Center','center':'Center Only','reset_size':'Reset Size',
    'manual_center':'Manual Center (Exact Middle)','manual_center_help':'Auto-centering detects the non-transparent part of the image and positions it based on that — for some images this detection may not give the result you expect. In that case, "Manual Center" places the image directly in the exact middle of the 64×64 canvas with no detection involved; you can also fine-tune it pixel by pixel using the X/Y fields or by dragging.',
    'offset_x':'X Position','offset_y':'Y Position','manual_center_done':'Image placed in the exact center ✓',
    'editor_help':'New images are automatically fitted and centered using Roblox’s default cursor size and placement as the reference. You can drag to change the position and use the size control to scale the cursor. Smoothing is disabled to preserve pixel sharpness.',
    'cancel':'Cancel','create':'Create','normal':'Normal','click':'Click','text':'Text Mode','shiftlock':'Shift Lock','choose_image':'Choose image','roblox_file':'Roblox file',
    'not_registered':'Not part of a saved pack (original/custom)','pack_applied':'applied in pack ✓','pack_apply':'Apply','pack_remove':'Remove','applied':'Applied ✓',
    'no_packs':'No saved packs yet.','packs_load_error':'Unable to load packs.','no_history':'No history yet.','history_load_error':'Unable to load history.',
    'use':'Use','delete':'Delete','backgrounds_load_error':'Unable to load backgrounds:','background_imported':'Background imported ✓','background_delete':'Delete background','background_delete_confirm':'Are you sure you want to delete "{name}"? This file will be permanently removed from the app data folder.','background_deleted':'Background deleted ✓',
    'default_bg_missing':'Default background not found','default_bg_restored':'Default background restored ✓','settings_read_error':'Unable to read settings:',
    'settings_load_error':'Unable to load settings; using defaults','status_unavailable':'Status unavailable',
    'auto_on':'Automatic repair enabled','auto_off':'Automatic repair disabled','boot_on':'Will launch at Windows startup','boot_off':'Windows startup launch disabled',
    'file_select_error':'Unable to select file:','image_invalid':'Unable to read image (invalid dimensions). Try another file.',
    'cursor_auto_fit':'Cursor automatically fitted and centered ✓','image_read_error':'Unable to read the image inside the .cur/.ico file.',
    'cursor_file_error':'Unable to read the .cur/.ico file:','image_load_error':'Unable to load image. The file may be corrupted or unsupported.',
    'preview_error':'Unable to draw preview:','cursor_centered':'Cursor centered ✓','save_error':'Save failed:','error':'Error:',
    'restore_done':'cursors restored to their originals ✓','no_backup':'No backup found to restore','pack_name':'Pack name:',
    'pack_saved':'pack saved ✓','pack_applied_toast':'applied ✓','pack_removed':'removed','history_applied':'applied ✓','history_deleted':'Removed from history',
    'background_error':'Unable to load backgrounds:','background_import_error':'Background imported ✓','language':'Language / Dil','turkish':'Türkçe','english':'English',
    'roblox_updated':'Roblox updated — {count} cursor(s) automatically reinstalled ✓','restore_done_count':'{count} cursor(s) restored to their originals ✓','pack_saved_named':'"{name}" pack saved ✓','saved_named':'"{name}" pack saved ✓',
    'colorize':'Colorize (generate color from black & white)','hue':'Hue','color_variations':'Generate Color Variations',
    'import_pack':'📥 Import','pack_from_active':'🖱️ Save Active Cursor as Pack','pack_from_active_short':'Save Active Cursor as Pack','pack_export':'Export','pack_dropzone_hint':'You can drag and drop a friend\'s .rbxcursor / .zip file here.',
    'pack_imported':'"{name}" pack imported ✓','pack_exported':'"{name}" pack exported ✓','pack_import_error':'Unable to import pack:','pack_export_error':'Unable to export pack:',
    'quickswitch_title':'Quick Pack Switching','quickswitch_desc':'Choose your own keyboard shortcut for each pack. It also works while Roblox is focused.',
    'quickswitch_assign':'⌨️ Assign Key','quickswitch_press':'Press a shortcut combination…','quickswitch_saved':'Shortcut saved ✓',
    'quickswitch_none':'— None —','quickswitch_saved':'Shortcut saved ✓','quickswitch_applied_toast':'Shortcut (Ctrl+Alt+{slot}) applied "{name}" ✓','quickswitch_error_toast':'Unable to apply shortcut:',
    'nav_animation':'Animation','settings_tab_general':'General','history_enabled':'Save History','history_enabled_desc':'Cursors you save in the editor are added to History. When off, nothing new is recorded; existing history is kept.','history_on':'History recording enabled','history_off':'History recording disabled',
    'donate':'Support','donate_tooltip':'Your support means faster updates & fixes — support the project ☕',
    'animcursor':'Animated','animcursor_title':'Animated Cursor (Beta)','animcursor_desc':'🧪 Beta feature: automatic state detection may occasionally misjudge in some games. Pick a .ANI file for each state. When a state has an animation assigned, Roblox\u2019s static cursor for that state is hidden and replaced by the native animated overlay. Removing it restores the real static cursor.','animcursor_none':'Not assigned — using the real static cursor','animcursor_applied':'Animated cursor applied ✓','animcursor_removed':'Animation removed, static cursor restored ✓',
    'context_preview':'Preview In Context','context_preview_title':'Context Preview','context_preview_help':'Test your cursor at its native pixel size inside a game-style scene.',
    'context_play':'PLAY','context_chat_placeholder':'Type in chat...','context_shiftlock':'Try Shift Lock mode','context_no_cursor':'No image saved yet for this cursor type.',
    'context_play_toast':'🎮 Not a real game — just a cursor test scene. This is how your cursors look!',
    'color_changer':'Change Color','color_changer_title':'Change Cursor Color',
    'color_changer_help':'Recolors all of your currently used cursors at once, without changing their size or position.',
    'color_changer_apply':'🎨 Apply','color_changer_none':'No active cursor found to recolor. Apply at least one cursor in Roblox first.',
    'color_changer_applied':'Cursor color updated ✓',
    'pack_name_required':'Pack name is required.','select_one_cursor_required':'You must select at least one cursor.',
    'pack_cursor_selection_title':'Cursor Selection','pack_cursor_selection_hint':'Choose which cursors to include in the pack. If you have custom cursors, the current selections are used automatically.',
    'packs_tab_normal':'Packs','packs_tab_animated':'🎞 Animation Packs','no_anim_packs':'No animation packs yet.','pack_anim_badge':'Animation pack',
    'new_anim_pack':'+ New Animation Pack','new_anim_pack_states_title':'Animations to Include','new_anim_pack_states_hint':'States that currently have a .ani assigned are listed here; both the animation and the current cursor image for that state are saved with this pack.',
    'new_anim_pack_none_assigned':'No state has an animation (.ani) assigned yet. Assign one first from the Animated Cursor tab.','new_anim_pack_none_selected':'You must select at least one animation state.',
    'context_preview_tooltip':'Try your cursors on a mock Roblox screen','color_changer_tooltip':'Change the color of all your currently used cursors at once',
    'restore_tooltip':'Revert to Roblox\u2019s own original cursors','pack_from_active_tooltip':'Save the cursors currently in use as a new pack',
    'app_tagline_tooltip':'RBX Cursor Studio — Created by: Carl',
    'update_install_btn':'Download & install (v{v})','update_available_inapp':'New version available: v{v} (you have v{cur}). It will be downloaded and installed from within the app.','update_downloading_btn':'Downloading… {p}%','update_downloading':'Downloading update: {p}%','update_restart_btn':'Restart & update','update_ready':'v{v} downloaded — restart to install','update_ready_toast':'Update ready (v{v}). Restart and install it from Settings > Updates.','update_restarting':'The app will close and update…','update_retry_btn':'Try again','update_dl_error':'Couldn\'t download the update.',
    'update_title':'Updates','update_desc':'Sends a single version query to GitHub on launch and tells you if a new version exists. Downloading and installing only start when you confirm.',
    'update_check_btn':'Check now','update_checking':'Checking…','update_auto_title':'Check automatically on launch','update_auto_on':'Update check on launch enabled','update_auto_off':'Update check on launch disabled',
    'update_available':'New version available: v{v} (you have v{cur}) — click to download','update_available_toast':'New version available: v{v}. Download it from Settings > Updates or the version tag at the top left.','update_open_btn':'Open release',
    'update_uptodate':'You\'re up to date (v{cur})','update_error':'Couldn\'t check (check your internet connection)','update_error_rate':'GitHub is rate-limiting requests right now; try again later',
    'animcursor_size_label':'Size ×','animcursor_speed_label':'Speed ×','animcursor_fps_label':'FPS (0 = original ANI)',
    'animcursor_center_auto':'Auto Center (exact middle)','animcursor_hotspot_x':'Hotspot X','animcursor_hotspot_y':'Hotspot Y',
    'animcursor_hotspot_hint':'(-1 = the ANI\u2019s own hotspot — applies while Auto Center is off)',
    'animcursor_pick_btn':'📂 Choose .ANI','animcursor_preview_btn':'👁️ Preview (6s)','animcursor_preview_running':'👁️ On desktop for 6s...','animcursor_clear_btn':'🗑️ Remove',
    'animcursor_live_title':'Currently active','animcursor_global_title':'Follow Sensitivity',
    'animcursor_global_desc':'The refresh interval of the cursor-tracking loop — applies to all states (arrow/click/text/shiftlock).',
    'animcursor_toggle_title':'Animation On / Off Hotkey','animcursor_toggle_desc':'Press this key to hide the animated cursor and bring your previous (static) cursors back; press again to re-enable the animation (works while Roblox is focused). If Roblox only reads cursor files at launch, restart Roblox to see the change. The on/off state is remembered, so it picks up where you left it next time.',
    'animcursor_toggle_on':'Animation: ON (click to turn off)','animcursor_toggle_off':'Animation: OFF (click to turn on)','animcursor_toggled_on':'Animated cursor turned on ✓','animcursor_toggled_off':'Animated cursor turned off',
    'animcursor_track_interval':'Follow Interval','animcursor_track_hint':'Lower ms = smoother/faster tracking (slightly more CPU), higher ms = fewer refreshes.',
    'animcursor_states_title':'State Animations','animcursor_states_sub':'{n}/4 states have an animation','animcursor_assigned':'ANI Assigned','animcursor_unassigned':'Not assigned',
    'animcursor_shared_title':'Settings — Shared by All States','animcursor_shared_hint':'Changes here are applied to all four states at once.',
    'animcursor_fullscreen_warning':'⚠️ While Roblox is in <strong>exclusive fullscreen</strong> mode, no overlay (ours included — same for Discord/Steam/RTSS) can draw over the game; that\u2019s a Windows restriction. Switch Roblox\u2019s display mode to "Fullscreen (Windowed) / Borderless" instead. If the animation isn\u2019t showing, try the <strong>Preview</strong> button first: it shows the cursor on your desktop for 6 seconds even if Roblox isn\u2019t open.'
  }
};

let currentLang = localStorage.getItem('rbx-language') || 'en';
function t(key, vars = {}) {
  const dict = LANG[currentLang] || LANG.tr;
  let s = dict[key] ?? LANG.tr[key] ?? key;
  return Object.keys(vars).reduce((out, k) => out.replaceAll(`{${k}}`, String(vars[k])), s);
}
function applyLanguage() {
  document.documentElement.lang = currentLang;
  document.querySelectorAll('[data-i18n]').forEach(el => { el.innerHTML = t(el.dataset.i18n); });
  document.querySelectorAll('[data-i18n-title]').forEach(el => { el.title = t(el.dataset.i18nTitle); });
  document.querySelectorAll('[data-i18n-aria]').forEach(el => { el.setAttribute('aria-label', t(el.dataset.i18nAria)); });
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => { el.placeholder = t(el.dataset.i18nPlaceholder); });
}
function setLanguage(lang) {
  if (!LANG[lang]) return;
  currentLang = lang;
  localStorage.setItem('rbx-language', lang);
  applyLanguage();
  if (window.rbx && typeof window.rbx.setLanguage === 'function') window.rbx.setLanguage(lang);
  if (typeof window.rbxLanguageChanged === 'function') window.rbxLanguageChanged();
}
if (window.rbx && typeof window.rbx.setLanguage === 'function') window.rbx.setLanguage(currentLang);
